
version: "3"
services:
  database:
    image: mongo:5
    restart: unless-stopped
    network_mode: "host"
    command: mongod --quiet --logpath /dev/null --port 27018
  server:
    build:
      context: .
      dockerfile: __SEALED__/test.Dockerfile
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - __SEALED__/.test.env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - "database"

