
version: "3"
services:
  database:
    image: mongo:5
    restart: unless-stopped
    command: mongod --quiet --logpath /dev/null
    expose:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
  server:
    build:
      context: .
      dockerfile: __SEALED__/Dockerfile.server
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - "database"
    expose:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SONGS_PORT}:${SONGS_PORT}"
      - "${AUTH_PORT}:${AUTH_PORT}"
  runner:
    build:
      context: .
      dockerfile: __SEALED__/Dockerfile.test
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - "database"
      - "server"

